### ISSUE TITLE
Missing support of arg "--config"

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/backstage-app#10]
## Issue

If I try to declare a configMap and pass it as as arg to the Deployment resource
```
    spec:
      containers:
        - name: backstage
          image: public.ecr.aws/cnoe-io/backstage:v0.0.3
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /app/app-config.yaml
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            #- secretRef:
            #    name: backstage-secrets
          volumeMounts:
            - mountPath: /app/app-config.yaml
              name: app-config
              subPath: app-config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: app-config
          name: app-config
```
then backstag's pod fails to start and reports as error:
```
node: bad option: --config
Stream closed EOF for backstage/backstage-785d979d46-n6d7w (backstage)
```

**Comment by cmoulliard** [comment]
I fixed the issue after I removed the arg from the Deployment
```
spec:
      containers:
        - name: backstage
          image: public.ecr.aws/cnoe-io/backstage:v0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - mountPath: /app/app-config.yaml
              name: app-config
              subPath: app-config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: app-config
          name: app-config
```
