### ISSUE TITLE
Software catalog

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/backstage-app#12]
## Question

Will cnoe provide and maintain a catalog of software or rely on an existing ?

```
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      locations:
        - target: https://github.com/janus-idp/backstage-showcase/blob/main/catalog-entities/all.yaml
          type: url
        - target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
          type: url
```
or
```
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      locations: []
```
