### ISSUE TITLE
Feature: `createArgoApplication` does not support destination server.

### ISSUE THREAD

**Issue by elamaran11** [cnoe-io/backstage-app#42]
### Have you searched for this feature request?

- [X] I searched but did not find similar requests

### Problem Statement

Currently Backstage uses roadie's ArgoCD [plugin](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/e5f30d0623ad5075dc38e65a348bb948ae64afe9/plugins/backend/backstage-plugin-argo-cd-backend/src/service/types.ts#L40) which supports Destination Server. But `createArgoApplication` does not support destination server. This is required for multi cluster deployments.  [This](https://github.com/cnoe-io/backstage-app/blob/135c0cb26f3e004a27a11edb6a4779035aff9805/packages/backend/src/plugins/argocd.ts#L125C21-L125C42) code which invokes this plugin does not support `Destination`. 

### Possible Solution

Currently Backstage uses roadie's ArgoCD [plugin](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/e5f30d0623ad5075dc38e65a348bb948ae64afe9/plugins/backend/backstage-plugin-argo-cd-backend/src/service/types.ts#L40) which supports Destination Server. But `createArgoApplication` does not support destination server. This is required for multi cluster deployments.  [This](https://github.com/cnoe-io/backstage-app/blob/135c0cb26f3e004a27a11edb6a4779035aff9805/packages/backend/src/plugins/argocd.ts#L125C21-L125C42) code which invokes this plugin does not support `Destination`. Appreciate if you can support this feature asap to multi cluster deployments from Backstage to Child clusters.

### Alternatives Considered

None.

**Comment by nabuskey** [comment]
I am all for this. One limitation we need to be clear is that the roadie backend plugin does not allow specifying deployment cluster by name. i.e. it expects a URL. We can expand our spec but if we truly want to support ArgoCD deployment target, we really should allow for names.

**Comment by elamaran11** [comment]
@nabuskey At this point we are expecting to support only Deployment Target by name. We are going by the assumption that target clusters are all configured and can be specified by name

**Comment by nabuskey** [comment]
> @nabuskey At this point we are expecting to support only Deployment Target by name. We are going by the assumption that target clusters are all configured and can be specified by name
> 
> 

Hmmm in that case, we can't fix it here. We'll have to ask in the roadie repo. We should verify first though. Last I checked, it wasn't possible to specify by name.

**Comment by elamaran11** [comment]
What i mean is it should support something like below if we can add that support in this repo. Let me try out, create an image and test.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argorollouts-dev
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.37.7
    helm:
      releaseName: argorollouts-dev
  destination:
    name: 'dev-cluster'
    namespace: argo-rollouts
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

```
